spring:
  datasource:
    url: jdbc:mysql://localhost:43306/bookAndMemo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: some1mine

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379


